import type { Metadata } from 'next';
import { DM_Sans, Geist, Inter } from 'next/font/google';
import './globals.css';

import './globals.css';
import { cn } from '@/lib/utils';

const dmSans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-dm-sans',
  fallback: ['sans-serif'],
});

const sansSarif = Inter({
  variable: '--font-sans-sarif',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${dmSans.variable} ${sansSarif.variable} relative`,
          'overflow-x-hidden',
        )}
      >
        {children}
      </body>
    </html>
  );
}
